name: am

on:
  push:
    branches:
      - master
      
  schedule:
    - cron: "* * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: c r
        uses: actions/checkout@v2

      - name: am
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_NAME }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "am"
          git push

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
